// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDJgWaWaWNQtwE4aSnXYcsDQM_DSJxET0',
    appId: '1:39005532776:web:4045efed8c3b96a5fd81dd',
    messagingSenderId: '39005532776',
    projectId: 'idute-97c56',
    authDomain: 'idute-97c56.firebaseapp.com',
    storageBucket: 'idute-97c56.appspot.com',
    measurementId: 'G-LG4QJZECML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi2e7noW7WgPWR4KS4BNpXXvlpZGzIJZA',
    appId: '1:39005532776:android:d8adbf4c51c92ef5fd81dd',
    messagingSenderId: '39005532776',
    projectId: 'idute-97c56',
    storageBucket: 'idute-97c56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvhZkqcWwowamDhPjA-Qx5Zd3w5A18P7g',
    appId: '1:39005532776:ios:91d8021cf46b82befd81dd',
    messagingSenderId: '39005532776',
    projectId: 'idute-97c56',
    storageBucket: 'idute-97c56.appspot.com',
    iosClientId: '39005532776-l42j54brm3anicmiqk8fevt17lhaqg07.apps.googleusercontent.com',
    iosBundleId: 'com.example.iduteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvhZkqcWwowamDhPjA-Qx5Zd3w5A18P7g',
    appId: '1:39005532776:ios:91d8021cf46b82befd81dd',
    messagingSenderId: '39005532776',
    projectId: 'idute-97c56',
    storageBucket: 'idute-97c56.appspot.com',
    iosClientId: '39005532776-l42j54brm3anicmiqk8fevt17lhaqg07.apps.googleusercontent.com',
    iosBundleId: 'com.example.iduteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDJgWaWaWNQtwE4aSnXYcsDQM_DSJxET0',
    appId: '1:39005532776:web:765dfa98a1608d43fd81dd',
    messagingSenderId: '39005532776',
    projectId: 'idute-97c56',
    authDomain: 'idute-97c56.firebaseapp.com',
    storageBucket: 'idute-97c56.appspot.com',
    measurementId: 'G-GM0WFL5FGW',
  );

}